/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/
import * as THREE from 'three'
import React, { useMemo, useRef } from 'react'
import { Float, useGLTF, Trail, Line, Sphere, Stars } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap'
import { useMediaQuery } from 'react-responsive'

function Electron({ radius = 2.75, speed = 6, ...props }) {
    const isMoblile = useMediaQuery(
        {
            maxWidth: 640
        }
    )
    const ref = useRef()
    useFrame((state) => {
        const t = state.clock.getElapsedTime() * speed
        ref.current.position.set(Math.sin(t) * radius, (Math.cos(t) * radius * Math.atan(t)) / Math.PI / 1.25, 0)
    })
  
    return (
        // <Float floatIntensity={5}>

        <group {...props} >
            <Trail  width={isMoblile?1:2} length={5} color={new THREE.Color(1, 15, 10)} attenuation={(t) =>  t}>
                <mesh ref={ref}>
                    <sphereGeometry args={[0.15]} />
                    <meshBasicMaterial color={[2, 15, 8]} toneMapped={false} />
                </mesh>
            </Trail>
        </group>
        // </Float>

    )
}

export default function ReactLogo(props) {
  

    const points = useMemo(() => new THREE.EllipseCurve(0, 0, 3, 1.15, 0, 2 * Math.PI, false, 0).getPoints(100), [])
    
    return (
        <group {...props} >
            <Electron position={[0, 0, 0.5]} speed={5}  />
            <Electron position={[0, 0, 0.5]} rotation={[0, 0, Math.PI / 3]} speed={5} />
            <Electron position={[0, 0, 0.5]} rotation={[0, 0, -Math.PI / 3]} speed={5} />
            <Sphere args={[0.35, 64, 64]}>
                <meshBasicMaterial color={[1, 15, 10]} toneMapped={false} />
            </Sphere>
        </group>
    )
}

useGLTF.preload('./models/react.glb')